export const SPAN_NAMES = {
  sessionCreate: "caisson.session.create",
  sandboxBoot: "caisson.sandbox.boot",
  brokerCall: "caisson.broker.call",
  policyEval: "caisson.policy.eval",
  approvalWait: "caisson.approval.wait",
  redaction: "caisson.redaction",
  auditWrite: "caisson.audit.write",
  auditBuffer: "caisson.audit.buffer",
  guestExec: "caisson.guest.exec",
  egressDenied: "caisson.egress.denied",
  snapshotBuild: "caisson.snapshot.build",
} as const;

export const ATTRIBUTE_KEYS = {
  sessionId: "session.id",
  sessionScopes: "session.scopes",
  driver: "driver",
  hardwareIsolated: "hardware_isolated",
  snapshotRef: "snapshot.ref",
  bootKind: "boot.kind",
  bootMs: "boot.ms",
  service: "service",
  method: "method",
  decision: "decision",
  actionId: "action.id",
  scopeUsed: "scope.used",
  roleUsed: "role.used",
  bundleVersion: "bundle.version",
  obligations: "obligations",
  evaluationMs: "eval.ms",
  approvalId: "approval.id",
  waitMs: "wait.ms",
  outcome: "outcome",
  durationMs: "duration.ms",
  resultBytes: "result.bytes",
  retries: "retries",
  redactionCount: "count",
  detectorsFired: "detectors.fired",
  auditEventType: "event.type",
  auditWritePath: "write.path",
  auditWriteMs: "write.ms",
  bufferKind: "buffer.kind",
  enqueueMs: "enqueue.ms",
  binary: "binary",
  exitCode: "exit.code",
  networkDestination: "network.destination",
  networkProtocol: "network.protocol",
  snapshotKind: "kind",
  snapshotSizeBytes: "size.bytes",
  snapshotBuildMs: "build.ms",
} as const;

export const METRIC_NAMES = {
  sandboxBootMs: "caisson_sandbox_boot_ms",
  brokerOverheadMs: "caisson_broker_overhead_ms",
  policyEvalMs: "caisson_policy_eval_ms",
  auditWriteMs: "caisson_audit_write_ms",
  approvalWaitSeconds: "caisson_approval_wait_seconds",
  actionsTotal: "caisson_actions_total",
  redactionsTotal: "caisson_redactions_total",
  sessionsActive: "caisson_sessions_active",
  sessionDurationSeconds: "caisson_session_duration_seconds",
  failClosedTotal: "caisson_fail_closed_total",
  auditCompletionBufferDepth: "caisson_audit_completion_buffer_depth",
  auditOrphanedActionsTotal: "caisson_audit_orphaned_actions_total",
  networkDeniedTotal: "caisson_network_denied_total",
} as const;

export type SpanName = (typeof SPAN_NAMES)[keyof typeof SPAN_NAMES];
